import zlib, struct, base64

def png(width, height, pixel_fn):
    raw = bytearray()
    for y in range(height):
        raw.append(0)  # filter type 0 (None)
        row = bytearray()
        for x in range(width):
            r, g, b = pixel_fn(x, y, width, height)
            row += bytes((r & 255, g & 255, b & 255))
        raw += row
    def chunk(typ, data):
        return struct.pack('>I', len(data)) + typ + data + struct.pack('>I', zlib.crc32(typ + data) & 0xffffffff)
    sig = b'\x89PNG\r\n\x1a\n'
    ihdr = struct.pack('>IIBBBBB', width, height, 8, 2, 0, 0, 0)  # 8-bit RGB
    idat = zlib.compress(bytes(raw), 9)
    return sig + chunk(b'IHDR', ihdr) + chunk(b'IDAT', idat) + chunk(b'IEND', b'')

def lerp(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))

def diag(top, bot):
    def f(x, y, w, h):
        t = (x / w + y / h) / 2
        return lerp(top, bot, t)
    return f

SIZE = 1000
images = {
    'g1.png': diag((255, 179, 102), (153, 51, 119)),   # warm sunset
    'g2.png': diag((120, 200, 170), (40, 90, 120)),    # teal / sea
    'g3.png': diag((150, 180, 255), (235, 150, 200)),  # blue / pink dusk
}

b64 = {}
for name, fn in images.items():
    data = png(SIZE, SIZE, fn)
    b64[name] = base64.b64encode(data).decode('ascii')

header = """// Bundled seed media for the demo (App Review) sandbox world.
//
// The /media route serves these PNGs directly for `seed/...` keys, so the demo
// feed has photos without any R2 objects or real family content. Migration 0006
// inserts the seed posts/comments that reference these filenames. Generated by
// scripts/gen_seed.py — abstract gradients, never real photos.

const SEED_IMAGES: Record<string, string> = {
"""

body = "".join(f"  '{name}':\n    '{val}',\n" for name, val in b64.items())

footer = """};

// Decode a bundled seed image to bytes, or null if the filename is unknown.
export function seedImage(filename: string): Uint8Array | null {
  const b64 = SEED_IMAGES[filename];
  if (!b64) return null;
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
"""

with open('/Users/allan.john/personal/git/familygram/backend/src/demo_seed.ts', 'w') as fh:
    fh.write(header + body + footer)

for name, val in b64.items():
    print(name, len(val), 'b64 chars')
